# Generated by Django 4.2.3 on 2025-04-20 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_likes_room_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='PlantGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('guide_picture', models.ImageField(upload_to='plant_guides/')),
                ('description', models.TextField()),
                ('germination', models.TextField()),
                ('transplanting', models.TextField()),
                ('harvest', models.TextField()),
                ('watering', models.TextField()),
                ('sunlight', models.TextField()),
                ('extra_care', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('growing_season', models.CharField(max_length=100)),
                ('days_to_harvest', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='plant_guides', to='base.plantcategory')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
