# Generated by Django 4.2.3 on 2025-04-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_plantcategory_plantguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vertical', 'Vertical'), ('Wall-mounted', 'Wall-mounted'), ('Hydroponics', 'Hydroponics'), ('Recycled Materials', 'Recycled Materials'), ('Aquaponics', 'Aquaponics')], max_length=50, unique=True)),
                ('description', models.TextField(help_text='General description of the cultivation technique')),
                ('setup_instructions', models.TextField(help_text='Step-by-step instructions on how to set up this cultivation system')),
                ('maintenance_tips', models.TextField(help_text='Tips for maintaining the cultivation system')),
                ('recommended_plants', models.TextField(help_text='Types of plants that work well with this technique')),
                ('space_requirements', models.TextField(help_text='Space requirements and ideal locations for this technique')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('estimated_cost', models.CharField(help_text='Estimated cost range for setting up this system', max_length=100)),
                ('materials_needed', models.TextField(help_text='List of materials needed for this cultivation technique')),
                ('benefits', models.TextField(help_text='Benefits of using this cultivation technique')),
                ('limitations', models.TextField(help_text='Limitations or challenges of this technique')),
                ('main_image', models.ImageField(help_text='Main image showing the cultivation technique', upload_to='technique_images/')),
                ('step_images', models.ImageField(blank=True, help_text='Additional images showing setup steps', null=True, upload_to='technique_steps/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cultivation Technique',
                'verbose_name_plural': 'Cultivation Techniques',
            },
        ),
    ]
