# Generated by Django 4.2.3 on 2025-05-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cultivationtechnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.message'),
        ),
    ]
