# Generated by Django 5.2 on 2025-05-09 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technique', models.CharField(choices=[('vertical', 'Vertical Farming'), ('wall', 'Wall-mounted Farming'), ('hydroponics', 'Hydroponics'), ('recycled', 'Recycled Materials'), ('aquaponics', 'Aquaponics')], max_length=20)),
                ('width', models.IntegerField(help_text='Width in centimeters')),
                ('height', models.IntegerField(help_text='Height in centimeters')),
                ('length', models.IntegerField(help_text='Length in centimeters')),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('materials_description', models.TextField()),
                ('extra_specifications', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='models3d/images/')),
                ('glb_model', models.FileField(blank=True, null=True, upload_to='models3d/glb/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating_image', 'Generating Image'), ('generating_model', 'Generating 3D Model'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cultivation_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_3d', to='base.cultivationtechnique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3D Cultivation Model',
                'verbose_name_plural': '3D Cultivation Models',
                'ordering': ['-created'],
            },
        ),
    ]
