# Generated by Django 5.2 on 2025-05-10 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cultivation3dmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('medal_type', models.CharField(choices=[('perfil', 'Perfil'), ('likes', 'Likes'), ('influencer', 'Influencer'), ('guias', 'Guías'), ('tecnicas', 'Técnicas')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medalla',
                'verbose_name_plural': 'Medallas',
            },
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.medal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medalla de Usuario',
                'verbose_name_plural': 'Medallas de Usuarios',
                'unique_together': {('user', 'medal')},
            },
        ),
    ]
