# Generated by Django 5.2 on 2025-05-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_medal_usermedal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationtechnique',
            name='name',
            field=models.CharField(choices=[('Vertical', 'Cultivo Vertical'), ('Pared', 'Cultivo en Pared'), ('Hidroponía', 'Hidroponía'), ('Materiales Reciclados', 'Materiales Reciclados'), ('Acuaponía', 'Acuaponía'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
