# Generated by Django 5.2 on 2025-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cultivationtechnique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation3dmodel',
            name='location',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cultivation3dmodel',
            name='technique',
            field=models.CharField(choices=[('vertical', 'Cultivo Vertical'), ('pared', 'Cultivo en Pared'), ('hidroponia', 'Hidroponía'), ('reciclados', 'Materiales Reciclados'), ('acuaponia', 'Acuaponía')], max_length=20),
        ),
    ]
