# Generated by Django 5.2 on 2025-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_cultivation3dmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationtechnique',
            name='difficulty_level',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantguide',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], max_length=50),
        ),
    ]
