# Generated by Django 5.2 on 2025-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_cultivationtechnique_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationtechnique',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Fácil'), ('Medium', 'Intermedio'), ('Hard', 'Difícil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantguide',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Fácil'), ('Medium', 'Intermedio'), ('Hard', 'Difícil')], max_length=50),
        ),
    ]
